add script and text
AdamPawlinski/java-script-8.6 pull request #1
Opened 2018-02-23 21:43 UTC by AdamPawlinski

zadanie 8.6 skończone - proszę o akceptację

2018-02-23 23:40 UTC, matwjablonski requested changes

2018-02-23 23:40 UTC, matwjablonski commented on js/script.js
> +if (value == 0) {
compare also type ;) always ;)

2018-02-23 23:40 UTC, matwjablonski commented on js/script.js
> +else if (value <= 0){
move it to previous line

2018-02-23 23:40 UTC, matwjablonski commented on js/script.js
> +else {
as above

2018-02-23 23:40 UTC, matwjablonski commented on index.html
> +<html lang="en">
doctype

2018-02-26 05:34 UTC, AdamPawlinski commented
Bugs fixed

2018-02-27 20:17 UTC, matwjablonski approved these changes

2018-09-11 04:38 UTC, merged